repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: black
        types: [python]
        language: system
      - id: lint
        name: lint
        entry: flake8
        types: [python]
        language: system
      - id: sort
        name: sort
        entry: isort
        types: [python]
        language: system
      - id: type-check
        name: type-check
        entry: mypy
        types: [python]
        language: system
