[tool.poetry]
name = "rsserpent"
version = "0.1.0"
description = "🐍 This snake helps you reconnect the Web, with RSS feeds!"
authors = ["Queensferry <queensferry.me@gmail.com>"]
license = "MIT"

[tool.poetry.extras]
plugin = ["rsserpent-plugin-example"]

[tool.poetry.dependencies]
python = "^3.6.2"
fastapi = "^0.65.2"
uvicorn = {extras = ["standard"], version = "^0.14.0"}
rsserpent-plugin-example = {git = "https://github.com/RSSerpent/rsserpent-plugin-example.git", optional = true}

[tool.poetry.dev-dependencies]
black = "^21.6b0"
flake8 = "^3.9.2"
mypy = "^0.902"
pre-commit = "^2.13.0"

[tool.black]
include = '\.pyi?$'
target-version = ["py36", "py37", "py38", "py39"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
