[tool.poetry]
name = "rsserpent"
version = "0.1.0"
description = "🐍 This snake helps you reconnect the Web, with RSS feeds!"
authors = ["Queensferry <queensferry.me@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.2"
fastapi = "^0.65.2"
uvicorn = {extras = ["standard"], version = "^0.14.0"}

[tool.poetry.dev-dependencies]
black = "^21.6b0"
mypy = "^0.902"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
